// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZyAjSeGbwIvFcIbc_KOE6xwJ3tc4WWWY',
    appId: '1:322677979446:web:cf0dc427cc9ab40f3c9b97',
    messagingSenderId: '322677979446',
    projectId: 'docencia-2023',
    authDomain: 'docencia-2023.firebaseapp.com',
    storageBucket: 'docencia-2023.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVArpNVBZThrCFD24rROlWVY3BzbcI-3U',
    appId: '1:322677979446:android:f40b6bc0136ba0b83c9b97',
    messagingSenderId: '322677979446',
    projectId: 'docencia-2023',
    storageBucket: 'docencia-2023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCo_nesmD71mQSdLC5CAchhJbaA_NKYK1Y',
    appId: '1:322677979446:ios:14eac2e6f00c6be23c9b97',
    messagingSenderId: '322677979446',
    projectId: 'docencia-2023',
    storageBucket: 'docencia-2023.appspot.com',
    iosBundleId: 'com.firebase.univalle.firebaseCrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCo_nesmD71mQSdLC5CAchhJbaA_NKYK1Y',
    appId: '1:322677979446:ios:5d7551e900e934533c9b97',
    messagingSenderId: '322677979446',
    projectId: 'docencia-2023',
    storageBucket: 'docencia-2023.appspot.com',
    iosBundleId: 'com.firebase.univalle.firebaseCrud.RunnerTests',
  );
}
